FROM node:22-slim
WORKDIR /app
COPY package*.json ./
RUN npm install --no-cache --legacy-peer-deps
RUN npm i -G @vue/cli
RUN npm i -G vue-tsc
RUN npm i -G @vue/cli-init@5.0.8
COPY . .
CMD ["npm", "run", "build"]